title: Dr. Ismail Baklouti
description: Ph.D. in Energy Engineering | Research Scientist
url: "https://ismail-baklouti.github.io"
baseurl: ""
email: "phd.ismail.baklouti@gmail.com"
alt_email: "ismail.baklouti@enim.u-monastir.tn"
social:
	orcid: "https://orcid.org/0000-0002-6847-9017"
	google_scholar: "https://scholar.google.com/citations?user=Af0tawMAAAAJ"
	linkedin: ""
	researchgate: ""
	twitter: ""